In [2]:
import numpy as np

In [1]:
x = [1,2,3]

In [4]:
np.array(x)

array([1, 2, 3])

In [5]:
x = [1, 2, 3.0]

In [6]:
np.array(x) # converts to float

array([1., 2., 3.])

In [8]:
np.array(x).dtype

dtype('float64')

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,3), 99) # full with number

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [14]:
np.linspace(1, 10, 5) # from 1 to 10 we have 5 steps in it

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
np.random.rand(5)

array([0.38709756, 0.63075045, 0.20475471, 0.8716636 , 0.07970246])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(5)[2] # creates a vector and 2nd indexed element is 1 rest are 0s

array([0., 0., 1., 0., 0.])

In [18]:
np.eye(10)[3]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])